CREATE DATABASE IF NOT EXISTS seat_system;
USE seat_system;

CREATE TABLE  IF NOT EXISTS SeatingChart (
    FLOOR_SEAT_SEQ INT PRIMARY KEY AUTO_INCREMENT,
    FLOOR_No INT NOT NULL,
    SEAT_No VARCHAR(10) NOT NULL
);


CREATE TABLE  IF NOT EXISTS Employee (
    EMP_ID CHAR(5) PRIMARY KEY,
    NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    FLOOR_SEAT_SEQ INT,
    FOREIGN KEY (FLOOR_SEAT_SEQ) REFERENCES SeatingChart(FLOOR_SEAT_SEQ)
);
